var NAVTREEINDEX0 =
{
"_h_t_m_l__c_s_s_pg.html":[5],
"_h_t_m_l__c_s_s_pg.html#css_sec":[5,1],
"_h_t_m_l__c_s_s_pg.html#html_sec":[5,0],
"drawing_pg.html":[3],
"drawing_pg.html#gamma_sec":[3,0],
"drawing_pg.html#subpixel_sec":[3,1],
"fonts_pg.html":[4],
"index.html":[],
"index.html#build_sec":[1],
"index.html#design_sec":[2],
"index.html#freetype_wrapper_sec":[2,0],
"index.html#into_sec":[0],
"index.html#layouter_sec":[2,1],
"index.html#output_sec":[2,3],
"index.html#tools_sec":[2,4],
"index.html#xhtml_sec":[2,2],
"pages.html":[],
"tutorial_pg.html":[6],
"tutorial_pg.html#tut_basic_sec":[6,0],
"tutorial_pg.html#tut_xhtml_sec":[6,1]
};
